### ISSUE TITLE
Potential Virus Alert

### ISSUE THREAD

**Issue by palmengladosTV** [ToiletCoders/WeatherGetter#2]
![grafik](https://user-images.githubusercontent.com/52998978/166168988-37308f54-fa93-4af3-8952-a409622e95e5.png)

**Comment by Fabus1184** [comment]
Kein Mensch benutzt den fucking Windows defender also machs aus und sei leise

**Comment by palmengladosTV** [comment]
I've installed the WeatherGetter and Windows Defender is telling me, that this programm is a virus. Please stop using malicious code in your programms...
